dist: trusty 
sudo: required
language: cpp
compiler: gcc

before_install:
    - sudo apt update -qq
    - sudo apt install -qq cmake

install: true

script:
    - cmake -G "Unix Makefiles"
    - make
    - ./test/unit_test
