dist: trusty 
sudo: required
language: cpp
install: make cmake gcc clang
compiler: gcc

jobs:
    include:
        - stage: compile
          script:
              - mkdir build
              - cd build
              - cmake -G "Unix Makefiles" ..
              - make
        - stage: test
          script: ./test/unit_test
