dist: trusty 
sudo: required
language: cpp
compiler: gcc

before_install:
    - sudo apt update -qq
    - sudo apt install -qq cmake

install: true

jobs:
    include:
        - stage: compile
          script:
              - mkdir build
              - cd build
              - cmake -G "Unix Makefiles" ..
              - make
        - stage: test
          script: ./test/unit_test
