dist: trusty 
sudo: required
language: cpp
compiler: gcc

matrix:
    include:
        - name: "Linux GCC 5 Test"
          os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5
          env:
              - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - name: "Linux GCC 6 Test"        
          os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6
          env:
              - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt update -qq
    - sudo apt install -qq cmake

install: true

script:
    - cmake -DCMAKE_VERBOSE_MAKEFILE=1 -G "Unix Makefiles"
    - make
    - ctest ./test
